### ISSUE TITLE
Db-sync takes too much time when syncing from genesis

### ISSUE THREAD

**Issue by KorayBarkin** [IntersectMBO/cardano-db-sync#1198] opened 2022-07-18 08:55 UTC
When I start the node as followed:

```
DOCKER_BUILDKIT=1 \
COMPOSE_DOCKER_CLI_BUILD=1 \
RESTORE_SNAPSHOT=https://update-cardano-mainnet.iohk.io/cardano-db-sync/12/db-sync-snapshot-schema-13-block-7498999-x86_64.tgz \
docker-compose up -d --build &&\
docker-compose logs -f
```

It says:

```
 Rolling back to genesis
 Deleting 7498999 blocks up to slot 66269743
```

I gave some time to figure it out but after 3 days of waiting it stuck here didn't changed at all. Then I decided to delete RESTORE_SNAPSHOT parameter to sync from genesis. It did start to sync but it is way too slow it's been running for 8 days and still at 272 epoch. For the last 2 days it came 272 from 271... if it keep going like that it'll get sync in a year. Any recommendations, help is appreciated thank you all in advance.

**Comment by kderme** [comment] 2022-07-18 21:29
Probably duplicate of https://github.com/input-output-hk/cardano-db-sync/issues/1196

**Comment by KorayBarkin** [comment] 2022-07-19 06:55
> Probably duplicate of #1196

The problem is not the rolling back to genesis when I start it with RESTORE_SNAPSHOT parameter, it is super slow while syncing via genesis it should be getting at epoch 272 in 8 days.

**Comment by erikd** [comment] 2022-07-19 07:15
> The problem is not the rolling back to genesis 

Then why mention it in the problem report?

> it is super slow while syncing via genesis it should be getting at epoch 272 in 8 days.

Yes, I would expect it to get to epoch `272` within 2 days.

You are almost certainly doing something wrong. Here are some possibilities:

* Are you meeting the [minimum system requirements](https://github.com/input-output-hk/cardano-db-sync#system-requirements)?
* Are you running with the database on an SSD rather than on an electro-mechanical disk?
* Are meeting the IOPS requirements?
* Are you running PostgreSQL on the same machine as `db-sync`?
* What are the machine specs? Slow machine will make syncing slow.

There are probably dozens of other ways of getting it wrong, but that is first set of possible issues.

**Comment by erikd** [comment] 2022-08-04 07:02
@KorayBarkin Any update on this? If your system takes 8 days to sync 272 epochs something is very, very wrong. On my systems (a VM on 4 year old hardware) I can sync from genesis to epoch 272 in under 12 hours.

**Comment by KorayBarkin** [comment] 2022-08-04 08:09
> @KorayBarkin Any update on this? If your system takes 8 days to sync 272 epochs something is very, very wrong. On my system (a VM on 4 year old hardware) I can sync from genesis to epoch 272 in under 12 hours.

I'm running on an AWS machine which has 8 cpu 32gb ram with 16k IOPS do you recommend me to update my instance with higher hardware?

**Comment by erikd** [comment] 2022-08-04 08:27
The performance of AWS instances can be significantly lower than what the hardware suggests. The [system requirements](https://github.com/input-output-hk/cardano-db-sync#system-requirements) explicitly states:

> Ensure that the machine has sufficient IOPS (Input/Output Operations per Second). Ie it should be 60k IOPS or better. Lower IOPS ratings will result in slower sync times and/or falling behind the chain tip.

**Comment by erikd** [comment] 2022-08-08 03:31
@KorayBarkin Can this be closed?

**Closed** 2024-01-24 01:57 UTC
Labels: bug, docker
